version: '3.8'

services:

  api:
    build: ./siralim-ultimate-api
    environment:
      - DATABASE_URL=postgresql://postgres:F00B4RYY@postgres:5432/siralim_ultimate_api
      - PORT=8000
    volumes:
      - ./siralim-ultimate-api:/code
    networks:
      - api
      - postgres
      - redis

  nginx:
    build: ./siralim-ultimate-nginx
    environment:
      - API_URL=api:8000
      - API_HOST=api:8000
      - PORT=80
      - PROTOCOL=http
    ports:
      - "80:80"
    networks:
      - api

  postgres:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=F00B4RYY
      - POSTGRES_DB=siralim_ultimate_api
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  redis:
    image: redis:6.2.5
    networks:
      - redis

volumes:
  postgres:

networks:
  api:
  postgres:
  redis: