version: '3.8'

services:

  api:
    build: ./siralim-ultimate-api
    environment:
      - DATABASE_URL=postgresql://postgres:F00B4RYY@postgres:5432/siralim_ultimate_api
      - PORT=8000
      - ALLOW_ORIGINS=localhost
    volumes:
      - ./siralim-ultimate-api:/code
    networks:
      - api
      - postgres
      - redis

  ui:
    build: ./siralim-ultimate-ui
    volumes:
      - ./siralim-ultimate-ui/src:/ui/src
      - ./siralim-ultimate-ui/public:/ui/public
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - ui

  nginx:
    build: ./siralim-ultimate-nginx
    environment:
      - API_URL=api:8000
      - API_HOST=api:8000
      - UI_URL=ui:3000
      - UI_HOST=ui:3000
      - PORT=80
      - PROTOCOL=http
    ports:
      - "80:80"
    networks:
      - api
      - ui

  postgres:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=F00B4RYY
      - POSTGRES_DB=siralim_ultimate_api
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.5
    networks:
      - redis

volumes:
  postgres:

networks:
  api:
  postgres:
  redis:
  ui: